auth:
  harvest:
    mail: 'kosta@savaslabs.com'
    pass: ''
    account: 'savaslabs'
  redmine:
    apikey: ''
    url: 'https://local.pm.savaslabs.com'
sync:
  projects:
    # Exclude Harvest project IDs from time entry processing.
    exclude:
      - "5990760"
      - "7077045"
      - "7174765"
