auth:
  harvest:
    mail: 'kosta@savaslabs.com'
    pass: ''
    account: 'chrisrusso'
  redmine:
    apikey: ''
    url: 'http://localhost:9292'
sync:
  projects:
    # Exclude Harvest project IDs from time entry processing.
    exclude:
      - "5990760"
      - "7077045"
      - "7174765"
