auth:
  harvest:
    mail: 'mail'
    pass: 'password'
    account: 'savaslabs'
  redmine:
    apikey: 'apiKey'
    url: 'http://app:3000'
  slack:
    webhook_url: 'url'
    # Set debug-user to a slack username to route all slack notifications to that user.
    # debug-user: '@tim'
sync:
 projects:
   # Exclude Harvest project IDs from time entry processing.
   exclude:
     - "5990760"
     - "7077045"
     - "7174765"
spellcheck:
  # Populate the project and page name for the spellcheck dictionary wiki in Redmine.
  # Those values can be obtained from the wiki's path as follows: pm.savaslabs.com/projects/[project_name]/wiki/[wiki_page_name]
  project_name: 'savaslabs'
  wiki_page_name: 'wiki_page_name'